export const SQUARE_VALUE_UPDATE = 'SQUARE_VALUE_UPDATE';
export const GRID_UPDATE = 'GRID_UPDATE';
export const SELECTED_BUTTON_UPDATE = 'SELECTED_BUTTON_UPDATE';
export const CURRENT_GRID_UPDATE = 'CURRENT_GRID_UPDATE';
export const CHANGE_BUTTON_LOCK_STATUS = 'CHANGE_BUTTON_LOCK_STATUS';
export const UPDATE_SELECTED_SMALL_SQUARE_INDEX = 'UPDATE_SELECTED_SMALL_SQUARE_INDEX';
export const INSERT_ACTION_HISTORY = 'INSERT_ACTION_HISTORY';
export const DELETE_ACTION_HISTORY = 'DELETE_ACTION_HISTORY';