export const SQUARE_VALUE_UPDATE = 'SQUARE_VALUE_UPDATE';
export const GRID_UPDATE = 'GRID_UPDATE';
export const SELECTED_BUTTON_UPDATE = 'SELECTED_BUTTON_UPDATE';
export const CURRENT_GRID_UPDATE = 'CURRENT_GRID_UPDATE';